/**
 * Static metadata for informational MDX posts.
 * Bodies live in content/posts/informational/*.mdx and are loaded only on the article page
 * (fs cannot run in Edge middleware, which imports allPosts via valid-paths).
 */
export const mdxInformationalArticles = [
  {
    id: "can-electric-bike-be-charged-at-home",
    slug: "can-electric-bike-be-charged-at-home",
    categorySlug: "guides",
    category: "Guides",
    contentType: "information",
    mdxSource: true,
    mdxFile: "can-electric-bike-be-charged-at-home.mdx",
    title: "Can You Charge an Electric Bike at Home? Full Guide",
    seoTitle: "Can You Charge an Electric Bike at Home? Full Guide",
    h1: "Charging Your E-Bike at Home: What New Owners Need to Know",
    metaDescription:
      "Yes, you can charge an electric bike at home. Here's how long it takes, what it costs, and how to do it safely without frying your battery.",
    heroImage: "/images/guides/can-electric-bike-be-charged-at-home-placeholder.webp",
    cardImage: "/images/guides/can-electric-bike-be-charged-at-home-placeholder.webp",
    articleHeroImage: "/images/guides/can-electric-bike-be-charged-at-home-placeholder.webp",
    heroImageAlt: "Electric bike battery charging from a standard home wall outlet",
    estimatedReadingTime: 8,
    publishedAt: "2026-07-20T18:00:00.000Z",
    updatedAt: "2026-07-20T18:00:00.000Z",
    relatedGuides: [
      {
        title: "Are Electric Bike Batteries Dangerous? What the Fire Data Shows",
        url: "/guides/are-electric-bike-batteries-dangerous",
      },
      {
        title: "Can Electric Bikes Get Wet? What You Need to Know",
        url: "/guides/can-electric-bikes-get-wet",
      },
      {
        title: "How Electric Bikes Work: Motors, Batteries & Sensors",
        url: "/guides/how-electric-bike-works",
      },
    ],
  },
  {
    id: "electric-bike-conversion-kits-worth-it",
    slug: "electric-bike-conversion-kits-worth-it",
    categorySlug: "guides",
    category: "Guides",
    contentType: "information",
    mdxSource: true,
    mdxFile: "electric-bike-conversion-kits-worth-it.mdx",
    title: "Are Electric Bike Conversion Kits Worth It? A Real Cost Breakdown",
    seoTitle: "Are Electric Bike Conversion Kits Worth It? A Real Cost Breakdown",
    h1: "Electric Bike Conversion Kits: Are They Actually Worth It?",
    metaDescription:
      "Thinking about converting your bike instead of buying an e-bike? Here's what conversion kits actually cost, the risks nobody mentions, and who they're really for.",
    heroImage: "/images/guides/electric-bike-conversion-kits-worth-it-placeholder.webp",
    cardImage: "/images/guides/electric-bike-conversion-kits-worth-it-placeholder.webp",
    articleHeroImage: "/images/guides/electric-bike-conversion-kits-worth-it-placeholder.webp",
    heroImageAlt: "Electric bike conversion kit motor and battery mounted on a regular bicycle",
    estimatedReadingTime: 8,
    publishedAt: "2026-07-20T17:00:00.000Z",
    updatedAt: "2026-07-20T17:00:00.000Z",
    relatedGuides: [
      {
        title: "How Much Does an Electric Bike Cost? 2026 Guide",
        url: "/guides/how-much-does-an-electric-bike-cost",
      },
      {
        title: "Are Electric Bikes Street Legal? 2026 State Guide",
        url: "/guides/are-electric-bikes-street-legal",
      },
      {
        title: "Are Electric Bikes Worth It? A Guide by Rider Type",
        url: "/guides/are-electric-bikes-worth-it",
      },
    ],
  },
  {
    id: "can-electric-bikes-climb-steep-hills",
    slug: "can-electric-bikes-climb-steep-hills",
    categorySlug: "guides",
    category: "Guides",
    contentType: "information",
    mdxSource: true,
    mdxFile: "can-electric-bikes-climb-steep-hills.mdx",
    title: "Can Electric Bikes Climb Steep Hills? The Real Answer",
    seoTitle: "Can Electric Bikes Climb Steep Hills? The Real Answer",
    h1: "E-Bike Hill Climbing: What Actually Determines Uphill Power",
    metaDescription:
      "Can electric bikes climb steep hills? Yes, but torque, motor type, and battery size matter more than you think. Here's what to know before buying.",
    heroImage: "/images/guides/can-electric-bikes-climb-steep-hills-placeholder.webp",
    cardImage: "/images/guides/can-electric-bikes-climb-steep-hills-placeholder.webp",
    articleHeroImage: "/images/guides/can-electric-bikes-climb-steep-hills-placeholder.webp",
    heroImageAlt: "Electric bike rider climbing a steep hill with pedal assist",
    estimatedReadingTime: 8,
    publishedAt: "2026-07-20T16:00:00.000Z",
    updatedAt: "2026-07-20T16:00:00.000Z",
    relatedGuides: [
      {
        title: "How Electric Bikes Work: Motors, Batteries & Sensors",
        url: "/guides/how-electric-bike-works",
      },
      {
        title: "Are Electric Bikes Worth It? A Guide by Rider Type",
        url: "/guides/are-electric-bikes-worth-it",
      },
      {
        title: "How Fast Do Electric Bikes Go? Speed Guide by Class",
        url: "/guides/how-fast-do-electric-bikes-go",
      },
    ],
  },
  {
    id: "how-fast-do-electric-bikes-go",
    slug: "how-fast-do-electric-bikes-go",
    categorySlug: "guides",
    category: "Guides",
    contentType: "information",
    mdxSource: true,
    mdxFile: "how-fast-do-electric-bikes-go.mdx",
    title: "How Fast Do Electric Bikes Go? Speed Guide by Class",
    seoTitle: "How Fast Do Electric Bikes Go? Speed Guide by Class",
    h1: "Electric Bike Speed Limits: What Every Class 1, 2, and 3 Rider Should Know",
    metaDescription:
      "How fast do electric bikes actually go? Here's the real breakdown by class, motor wattage, and country, plus whether a faster ebike is worth it.",
    heroImage: "/images/guides/how-fast-do-electric-bikes-go-placeholder.webp",
    cardImage: "/images/guides/how-fast-do-electric-bikes-go-placeholder.webp",
    articleHeroImage: "/images/guides/how-fast-do-electric-bikes-go-placeholder.webp",
    heroImageAlt: "Electric bike rider checking speed on a Class 3 e-bike commute",
    estimatedReadingTime: 8,
    publishedAt: "2026-07-20T15:00:00.000Z",
    updatedAt: "2026-07-20T15:00:00.000Z",
    relatedGuides: [
      {
        title: "Are Electric Bikes Street Legal? 2026 State Guide",
        url: "/guides/are-electric-bikes-street-legal",
      },
      {
        title: "How Electric Bikes Work: Motors, Batteries & Sensors",
        url: "/guides/how-electric-bike-works",
      },
      {
        title: "Are Electric Bikes Worth It? A Guide by Rider Type",
        url: "/guides/are-electric-bikes-worth-it",
      },
    ],
  },
  {
    id: "how-electric-bike-works",
    slug: "how-electric-bike-works",
    categorySlug: "guides",
    category: "Guides",
    contentType: "information",
    mdxSource: true,
    mdxFile: "how-electric-bike-works.mdx",
    title: "How Electric Bikes Work: Motors, Batteries & Sensors",
    seoTitle: "How Electric Bikes Work: Motors, Batteries & Sensors",
    h1: "What's Actually Happening Inside an E-Bike When You Pedal",
    metaDescription:
      "Curious how an e-bike actually works? Here's a plain-English breakdown of the motor, battery, sensors, and throttle, plus a diagram of the full system.",
    heroImage: "/images/guides/how-electric-bike-works-placeholder.webp",
    cardImage: "/images/guides/how-electric-bike-works-placeholder.webp",
    articleHeroImage: "/images/guides/how-electric-bike-works-placeholder.webp",
    heroImageAlt: "Electric bike motor, battery, and sensor system explained",
    estimatedReadingTime: 8,
    publishedAt: "2026-07-20T14:00:00.000Z",
    updatedAt: "2026-07-20T14:00:00.000Z",
    relatedGuides: [
      {
        title: "Are Electric Bikes Street Legal? 2026 State Guide",
        url: "/guides/are-electric-bikes-street-legal",
      },
      {
        title: "Are Electric Bike Batteries Dangerous? What the Fire Data Shows",
        url: "/guides/are-electric-bike-batteries-dangerous",
      },
      {
        title: "How Much Does an Electric Bike Cost? 2026 Guide",
        url: "/guides/how-much-does-an-electric-bike-cost",
      },
    ],
  },
  {
    id: "can-electric-bikes-get-wet",
    slug: "can-electric-bikes-get-wet",
    categorySlug: "guides",
    category: "Guides",
    contentType: "information",
    mdxSource: true,
    mdxFile: "can-electric-bikes-get-wet.mdx",
    title: "Can Electric Bikes Get Wet? What You Need to Know",
    seoTitle: "Can Electric Bikes Get Wet? What You Need to Know",
    h1: "Riding and Charging Your E-Bike in the Rain: A Practical Guide",
    metaDescription:
      "Can electric bikes get wet? Yes, most handle rain fine. Here's what IP ratings mean, what to avoid, and how to charge safely after a wet ride.",
    heroImage: "/images/guides/can-electric-bikes-get-wet-placeholder.webp",
    cardImage: "/images/guides/can-electric-bikes-get-wet-placeholder.webp",
    articleHeroImage: "/images/guides/can-electric-bikes-get-wet-placeholder.webp",
    heroImageAlt: "Electric bike ridden through light rain on a wet city street",
    estimatedReadingTime: 7,
    publishedAt: "2026-07-18T13:00:00.000Z",
    updatedAt: "2026-07-18T13:00:00.000Z",
    relatedGuides: [
      {
        title: "Are Electric Bike Batteries Dangerous? What the Fire Data Shows",
        url: "/guides/are-electric-bike-batteries-dangerous",
      },
      {
        title: "Are Electric Bikes Worth It? A Guide by Rider Type",
        url: "/guides/are-electric-bikes-worth-it",
      },
      {
        title: "How Much Does an Electric Bike Cost? 2026 Guide",
        url: "/guides/how-much-does-an-electric-bike-cost",
      },
    ],
  },
  {
    id: "are-electric-bikes-worth-it",
    slug: "are-electric-bikes-worth-it",
    categorySlug: "guides",
    category: "Guides",
    contentType: "information",
    mdxSource: true,
    mdxFile: "are-electric-bikes-worth-it.mdx",
    title: "Are Electric Bikes Worth It? A Guide by Rider Type",
    seoTitle: "Are Electric Bikes Worth It? A Guide by Rider Type",
    h1: "Is an E-Bike Worth It? It Really Depends on How You'll Use It",
    metaDescription:
      "Are electric bikes worth it? It depends on who's riding. Here's a real breakdown by commuter, senior, gig worker, and fitness rider.",
    heroImage: "/images/guides/are-electric-bikes-worth-it-placeholder.webp",
    cardImage: "/images/guides/are-electric-bikes-worth-it-placeholder.webp",
    articleHeroImage: "/images/guides/are-electric-bikes-worth-it-placeholder.webp",
    heroImageAlt: "Rider considering whether an electric bike is worth the investment",
    estimatedReadingTime: 8,
    publishedAt: "2026-07-18T12:00:00.000Z",
    updatedAt: "2026-07-18T12:00:00.000Z",
    relatedGuides: [
      {
        title: "How Much Does an Electric Bike Cost? 2026 Guide",
        url: "/guides/how-much-does-an-electric-bike-cost",
      },
      {
        title: "Is It Worth Getting an Electric Bike? The Real Answer for 2026",
        url: "/electric-bikes/is-it-worth-getting-electric-bike",
      },
      {
        title: "Are Electric Bike Batteries Dangerous? What the Fire Data Shows",
        url: "/guides/are-electric-bike-batteries-dangerous",
      },
    ],
  },
  {
    id: "how-much-does-an-electric-bike-cost",
    slug: "how-much-does-an-electric-bike-cost",
    categorySlug: "guides",
    category: "Guides",
    contentType: "information",
    mdxSource: true,
    mdxFile: "how-much-does-an-electric-bike-cost.mdx",
    title: "How Much Does an Electric Bike Cost? 2026 Guide",
    seoTitle: "How Much Does an Electric Bike Cost? 2026 Guide",
    h1: "Electric Bike Pricing in 2026: What You'll Really Pay",
    metaDescription:
      "Real 2026 e-bike price breakdown by tier, plus the hidden costs (insurance, maintenance, battery swaps) most guides skip.",
    heroImage: "/images/guides/how-much-does-an-electric-bike-cost-placeholder.webp",
    cardImage: "/images/guides/how-much-does-an-electric-bike-cost-placeholder.webp",
    articleHeroImage: "/images/guides/how-much-does-an-electric-bike-cost-placeholder.webp",
    heroImageAlt: "Electric bike price tiers and ownership costs for 2026 buyers",
    estimatedReadingTime: 8,
    publishedAt: "2026-07-18T11:00:00.000Z",
    updatedAt: "2026-07-18T11:00:00.000Z",
    relatedGuides: [
      {
        title: "Is It Worth Getting an Electric Bike?",
        url: "/electric-bikes/is-it-worth-getting-electric-bike",
      },
      {
        title: "Are Electric Bike Batteries Dangerous? What the Fire Data Shows",
        url: "/guides/are-electric-bike-batteries-dangerous",
      },
    ],
  },
  {
    id: "are-electric-bikes-street-legal",
    slug: "are-electric-bikes-street-legal",
    categorySlug: "guides",
    category: "Guides",
    contentType: "information",
    mdxSource: true,
    mdxFile: "are-electric-bikes-street-legal.mdx",
    title: "Are Electric Bikes Street Legal? 2026 State Guide",
    seoTitle: "Are Electric Bikes Street Legal? 2026 State Guide",
    h1: "Electric Bike Laws Explained: What's Legal and What Isn't",
    metaDescription:
      "Confused about e-bike laws? Here's what's legal by class, by state, and by country, plus what happens when a bike crosses the line into moped territory.",
    heroImage: "/images/guides/are-electric-bikes-street-legal-placeholder.webp",
    cardImage: "/images/guides/are-electric-bikes-street-legal-placeholder.webp",
    articleHeroImage: "/images/guides/are-electric-bikes-street-legal-placeholder.webp",
    heroImageAlt: "Electric bike on a city street illustrating street-legal e-bike riding",
    estimatedReadingTime: 7,
    publishedAt: "2026-07-18T09:00:00.000Z",
    updatedAt: "2026-07-18T09:00:00.000Z",
    relatedGuides: [
      {
        title: "Is It Worth Getting an Electric Bike?",
        url: "/electric-bikes/is-it-worth-getting-electric-bike",
      },
      {
        title: "Are Electric Bike Batteries Dangerous? What the Fire Data Shows",
        url: "/guides/are-electric-bike-batteries-dangerous",
      },
    ],
  },
  {
    id: "are-electric-bike-batteries-dangerous",
    slug: "are-electric-bike-batteries-dangerous",
    categorySlug: "guides",
    category: "Guides",
    contentType: "information",
    mdxSource: true,
    mdxFile: "are-electric-bike-batteries-dangerous.mdx",
    title: "Are Electric Bike Batteries Dangerous? What the Fire Data Shows",
    seoTitle: "Are Electric Bike Batteries Dangerous? What the Fire Data Shows",
    h1: "Are E-Bike Batteries Actually Dangerous? Here's What the Numbers Say",
    metaDescription:
      "Are electric bike batteries dangerous? Here's what fire department and CPSC data actually show, plus how to charge and store yours safely.",
    heroImage: "/images/guides/are-electric-bike-batteries-dangerous-placeholder.webp",
    cardImage: "/images/guides/are-electric-bike-batteries-dangerous-placeholder.webp",
    articleHeroImage: "/images/guides/are-electric-bike-batteries-dangerous-placeholder.webp",
    heroImageAlt:
      "Electric bike battery pack charged on a hard floor away from living spaces",
    estimatedReadingTime: 8,
    publishedAt: "2026-07-18T10:00:00.000Z",
    updatedAt: "2026-07-18T10:00:00.000Z",
    relatedGuides: [
      {
        title: "Are Electric Bikes Street Legal? 2026 State Guide",
        url: "/guides/are-electric-bikes-street-legal",
      },
      {
        title: "Is It Worth Getting an Electric Bike?",
        url: "/electric-bikes/is-it-worth-getting-electric-bike",
      },
    ],
  },
  {
    id: "is-it-worth-getting-electric-bike",
    slug: "is-it-worth-getting-electric-bike",
    categorySlug: "electric-bikes",
    category: "Electric Bikes",
    contentType: "information",
    mdxSource: true,
    mdxFile: "is-it-worth-getting-electric-bike.mdx",
    title: "Is It Worth Getting an Electric Bike? The Real Answer for 2026",
    seoTitle: "Is It Worth Getting an Electric Bike? The Real Answer for 2026",
    h1: "Is It Worth Getting an Electric Bike? The Real Answer for 2026",
    metaDescription:
      "Thinking about buying an electric bike? Discover if e-bikes are worth the investment with our honest breakdown of costs, benefits, and who should (and shouldn't) buy one.",
    heroImage:
      "/images/is-it-worth-getting-an-electric-bike/is-it-worth-getting-electric-bike-hero.webp",
    cardImage:
      "/images/is-it-worth-getting-an-electric-bike/is-it-worth-getting-electric-bike.webp",
    articleHeroImage:
      "/images/is-it-worth-getting-an-electric-bike/is-it-worth-getting-electric-bike.webp",
    heroImageAlt: "Modern electric bike parked on city street with commuter lifestyle",
    estimatedReadingTime: 9,
    publishedAt: "2025-01-15T09:00:00.000Z",
    updatedAt: "2025-01-15T09:00:00.000Z",
    relatedGuides: [
      {
        title: "How Much Does an Electric Bike Cost? 2026 Guide",
        url: "/guides/how-much-does-an-electric-bike-cost",
      },
      {
        title: "Are Electric Bikes Street Legal? 2026 State Guide",
        url: "/guides/are-electric-bikes-street-legal",
      },
      {
        title: "Are Electric Bike Batteries Dangerous? What the Fire Data Shows",
        url: "/guides/are-electric-bike-batteries-dangerous",
      },
    ],
  },
];
